.gitattributes

Github limit is 100mb so there won't be issues with git-lfs quota anymore

Add MobileRTC back to git

---

android/build.gradle

I already had and know how to reproduce this issue. 
Android didn't work without gradle update.
Issue: https://github.com/mieszko4/react-native-zoom-us/issues/35
It is fixed for me after update.

fix android autolinking

---

.github/workflows/npm-publish.yml
.gitignore
.npmignore
index.ts
package-lock.json
package.json
tsconfig.json

I found that typescript linter doesn't see package.
So I decided to copy compiler that I frequently use for ts libraries.
After compilation, I found that bug was inside `index.ts`. So compiler is not so necessary, but I think it may be useful for future.
There is also hooks for npm publish. It will run automatically.
If there is any errors, `npm publish` will crash before publishing

Manage typescript compiler

---

docs/IOS-SCREENSHARE.md
index.ts
ios/RNZoomUs.m

This PR adds support for sharing the user's full screen under iOS using ReplayKit (with an appropriate app extension). There are still changes that need to be made in the xcode project for the app in order to enable it (documented in `docs/IOS-SCREENSHARE.md`), but these changes allow the library to be used to enable screen sharing without any further modification of the library code.

Add support for full screen sharing under iOS

---

android/src/main/java/ch/milosz/reactnative/RNZoomUsModule.java

We actually want to be able to disable the video preview on Android, too, so this makes Android respect the same flag as iOS. Note that this is a backward-incompatible change because previously this flag did nothing under Android.

Allow video preview to be disabled on Android too

---

android/build.gradle
android/libs/build.gradle

As far as I can tell, by adding `libs/build.gradle`, we can use `fileTree()` for the release build as well.

Add build.gradle file so we can use fileTree

---

android/src/main/java/ch/milosz/reactnative/RNZoomUsModule.java
index.ts
ios/RNZoomUs.h
ios/RNZoomUs.m

This adds RN events on:
* Auth initialization
* Meeting status changes
* Meeting departure
* Screen sharing start/stop
We could fire events on other things as well, but these are the ones that I have needed to handle screen sharing in our React Native app smoothly. I'm not certain this is the right approach, since—particularly on Android with InMeetingServiceListener methods—it results in a rather large amount of additional code, but it works well for us.

Fire RN events on meeting- and auth events

---

README.md
RNZoomUs.podspec

Looks like there is no breaking changes.
Related to https://github.com/mieszko4/react-native-zoom-us/issues/70

IOS SDK 5.4.54802.0124

---

README.md
android/src/main/java/ch/milosz/reactnative/RNZoomUsModule.java
index.ts
ios/RNZoomUs.m

This patch adds support for SDK initialization using JWT as alternative of classic SDK Key & Secret
See: 
- https://zoom.github.io/zoom-sdk-android/us/zoom/sdk/ZoomSDK.html#initialize-android.content.Context-us.zoom.sdk.ZoomSDKInitializeListener-us.zoom.sdk.ZoomSDKInitParams-
- https://marketplace.zoom.us/docs/sdk/native-sdks/iOS/mastering-zoom-sdk/sdk-initialization
- https://marketplace.zoom.us/docs/sdk/native-sdks/android/mastering-zoom-sdk/sdk-initialization

Add support for JWT SDK initialization

---

android/src/main/java/ch/milosz/reactnative/RNZoomUsModule.java
index.ts

Fix crash: https://github.com/mieszko4/react-native-zoom-us/issues/98
Extra:
- isInitialized - new method for js (forget to add to IOS)
- removed isInitialized variable, because it is not used by code. Other methods check it from zoomSdk
I tested and it worked ok. Multiple calls of init look ok.
It would be great to add some eslint for ts file. My IDEA inherit it from project and I see whole file in red :)

fix crash on initialize

---

CHANGELOG.md
README.md
RNZoomUs.podspec
index.ts
ios/RNZoomUs.m
package.json

I don't know why they removed participantID. Field is useful.
I removed extension from main file to make it flexible (to choose between js or ts file)
I use sometimes ts variant when clone project. Also it allows to install library directly from github.
https://github.com/mieszko4/react-native-zoom-us/issues/109

IOS SDK 5.7.1.644

---

android/build.gradle

flexbox 2.0.1 exist in jcenter which is deprecated and new react native version uses mavenCentral, flexbox 3 exist in google maven which is used in react native also.
same goes for exoplayer.

Update flexbox and exoplayer versions.

---

android/src/main/java/ch/milosz/reactnative/RNZoomUsModule.java

When I initially created this option I unmuted the audio of the user which is not what this should do. It should just connect to audio and keep the audio status untouched as this is part of the meeting settings.

Dont unmute audio on connectAudioWithVoIP 

---

ios/RNZoomUs.m

* It made the app crash when calling with out the param
* This param is not in line with the android version

Removed unused parameter in stopShareScreen on iOS

---

android/src/main/java/ch/milosz/reactnative/RNZoomUsModule.java
docs/EVENTS.md

Fixed #198 
So we started using the new onSharingStatus event listener, we left the old deprecated onShareActiveUser for backwards compatibility.
* onShareActiveUser has been deprecated
* Im keeping it for now for events backwards compatibility
* I renamed some events following what onSharingStatus gets
* Events added: screenShareStartedBySelf, screenShareStoppedBySelf, screenShareStoppedByUser, screenShareOtherSharing, screenSharePause, screenShareResume
* Every one of this events now also sends the userId
* We might want to remove onShareActiveUser event listener in next major version
* Added new events to docs

Fixed issue with screen share events

---

CHANGELOG.md
README.md
android/build.gradle
android/src/main/java/ch/milosz/reactnative/RNZoomUsModule.java
docs/LINKING.md

* https://8xmdmkir8ctlkfj8dttx.noticeable.news/publications/meeting-sdk-android-v5-10-1
* https://8xmdmkir8ctlkfj8dttx.noticeable.news/publications/meeting-sdk-android-v5-10-3
Possible breaking changes:
* `compileSdkVersion` is `31`
* `buildToolsVersion` is `30.0.2`
* `minSdkVersion` is `21`
* `targetSdkVersion` is `31`
For Android 12 added:
* `android.permission.BLUETOOTH_SCAN`
Closes https://github.com/mieszko4/react-native-zoom-us/issues/201
The following procedure covers testing of the bridge (initialization and join meeting only).
1. [x] Development: `yarn run android`
1. [x] Development: `yarn run android`
2. [x] Release: `cd android && ./gradlew assembleRelease && cd ..`, `adb install android/app/build/outputs/apk/release/app-release.apk`
1. [x] Development: …

feat: upgrade Android to 5.10.3 SDK

---

.eslintrc
README.md
android/src/main/java/ch/milosz/reactnative/RNZoomUsModule.java
docs/TROUBLESHOOTING.md
index.ts
ios/RNZoomUs.m
native.ts
src/events.ts

I want to give some methods with typing for existing events.
I chose only specific group of events for now, which looks good for me: MeetingStatus (ios + android) events.
I made another channel for events for 2 reasons:
1) currently all events are going in 1 channel and it can make confusing behaviour, because there are many events. Most of them can be not normalised.
2) I want to avoid breaking changes for apps that using existing events at the moment.

Add methods for event subscribing (MeetingStatus group).

---

CHANGELOG.md
README.md
RNZoomUs.podspec

* https://8xmdmkir8ctlkfj8dttx.noticeable.news/publications/meeting-sdk-v5-10-3-patch
* https://8xmdmkir8ctlkfj8dttx.noticeable.news/publications/meeting-sdk-ios-v5-10-6
* https://8xmdmkir8ctlkfj8dttx.noticeable.news/publications/meeting-sdk-ios-v5-11-0
The following procedure covers testing of the bridge (initialization and join meeting only).
1. [ ] Development: `yarn run android`
1. [ ] Development: `yarn run android`
2. [ ] Release: `cd android && ./gradlew assembleRelease && cd ..`, `adb install android/app/build/outputs/apk/release/app-release.apk`
1. [ ] Development: `yarn run ios` (Note that M1 chip is not supported by Zoom SDK)
Note: You will need to allow to install app; look for: Settings -> General -> Device Management -> Apple Development
1. [x] …

feat: Upgrade iOS to 5.11.0.3907

---

CHANGELOG.md
android/src/main/java/ch/milosz/reactnative/RNZoomUsModule.java
android/src/main/java/ch/milosz/reactnative/RNZoomUsVideoView.java
index.ts

ZoomSDK for Android complaints about code not being executed on main thread - this PR makes sure to execute ZoomSDK code on main thread, id adds logs, try/catch, cleans up logic.
It also fixes issues with not showing meeting and lost listeners after backgrounding then foregrounding the app.
Finally it adds `noMeetingErrorMessage` to `startMeeting` params.
Closes https://github.com/mieszko4/react-native-zoom-us/issues/192
Closes https://github.com/mieszko4/react-native-zoom-us/issues/166
Hopefully closes  https://github.com/mieszko4/react-native-zoom-us/issues/162
The following procedure covers testing of the bridge (initialization and join meeting only).
1. [x] Development: `yarn run android`
1. [x] Development: `yarn run android`
2. [x] Release: `cd android && ./gradlew assembleRelease …

feat: prepapare android for 5.11

---

README.md
RNZoomUs.podspec

Looks like there is no breaking changed for native side.
I made minimal test by creating meeting. Works ok.
Should help for: https://github.com/mieszko4/react-native-zoom-us/issues/224

IOS 5.11.3.4099

---

RNZoomUs.podspec

Should fix issue mentioned at https://github.com/mieszko4/react-native-zoom-us/issues/224#issuecomment-1210423211
I made minimal test with joining meeting.
Btw. I also republished previous sdk `5.11.3.4099` with correct version, so potentially issue will be solved. But I think it is better to bump version, to avoid cache issues.

IOS SDK 5.11.3.4099.1

---

android/src/main/java/ch/milosz/reactnative/RNZoomUsModule.java
index.ts
ios/RNZoomUs.m

I added two props into InitializeSettings:
1. disableMinimizeMeeting
- iOS-only property
- From v6.12.0, the minimize meeting button has been changed to a header back button.
- If you set this prop to true, you can disable minimize option and hide back button by this fix.
- Tested in iOS
2. disableClearWebKitCache
- My app is a web app, and since v6.7.0, leaveMeeting of ZoomSDK clear web storage.
- While looking for a solution, I found the disableClearWebKitCache property.
- Web storage is preserved through this fix : Tested in both iOS and Android.
---
- MeetingSettings change is not working in initialize method, so I fixed a spot to change settings.
- I fixed how to retrieve BOOL value from dictionary in iOS.
---
One more extra fix: { autoConnectAudio: true } was not working in iOS
- It …

feat: add props to InitializeSettings

---

README.md
android/build.gradle
android/src/main/java/ch/milosz/reactnative/RNZoomUsModule.java

It is update for https://github.com/mieszko4/react-native-zoom-us/pull/219
Note that I selected sub branch for update.
I only added android sdk 5.12.2  and merged master.
Issue with `__emutls_get_address` (https://github.com/mieszko4/react-native-zoom-us/pull/219) is still exists.

Android sdk 5.12.2

---

android/build.gradle

Fix after releasing https://github.com/mieszko4/react-native-zoom-us/pull/314
Closes https://github.com/mieszko4/react-native-zoom-us/issues/327

fix: update android dependencies from 5.16.2

---

README.md
android/build.gradle
android/proguard.cfg
android/src/main/AndroidManifest.xml
android/src/main/java/ch/milosz/reactnative/RNZoomUsModule.java

Tested on Google Pixel 9 Pro running Android 15, and my emulator running Android 14 on MacOS. All of this testing was done in release mode via `yarn android --mode=release` because I was having issues in dev mode with the app not being able to see my running metro instance.

Upgrade Android zoom meeting sdk to 6.15.23231
