- RNZoomUs.podspec
- android/src/main/java/ch/milosz/reactnative/RNZoomUsModule.java
- index.js
- index.ts
- ios/RNZoomUs.m
- package.json
New:
- typescript
- Add object support
- Extended functionality
Breaking changes: 
- All methods requires object now. (Instead of params list)
If it is ok, I will add docs.
P.S. react-native works ok with lib `.ts` files, so I don't add compilation for now. I'll add once it will be necessary. (webpack case probably)
> extend functionality + typescript support

- README.md
- docs/LINKING.md
- docs/UPGRADING.md
- Moved linking to separate file.
- Added upgrading for 5.0
- updated methods on README.md
> docs for 5.0

- README.md
- android/build.gradle
Changes:
- Revert PR: https://github.com/mieszko4/react-native-zoom-us/pull/36
- update readme
It will solve issues like this: https://github.com/mieszko4/react-native-zoom-us/issues/43
> android: revert linking PR

- index.ts
- package.json
added validation for initialize. It will help to avoid crashes.
Possible fix for: https://github.com/mieszko4/react-native-zoom-us/issues/44
> Add more validation

- .npmignore
- tsconfig.json
fix: https://github.com/mieszko4/react-native-zoom-us/issues/49
> fix incorrect es compilation

- android/build.gradle
- android/src/main/java/ch/milosz/reactnative/RNZoomUsModule.java
- index.ts
- ios/RNZoomUs.m
Just adding some methods that I have being using in production for some months already and might be useful to other users.
Maybe the autoconnect to audio on join should be optional. Let me know if this changes make sense to merge and ill do the changes.
> Added leaveMeeting and connectAudio methods and autoconnect to audio on join

- android/src/main/java/ch/milosz/reactnative/RNZoomUsModule.java
Added MeetingViewOptions to hide meeting Info, participants button, share button, more button, leave button. Also added customized title.
> added MeetingViewsOptions

- android/src/main/java/ch/milosz/reactnative/RNZoomUsModule.java
added meeting view options for start meeting to remove meeting info, participants button and no invite. Please, merge this asap. I did the smoke testing as well.
> added MeetingViewsOptions for start meeting

- android/src/main/java/ch/milosz/reactnative/RNZoomUsModule.java
- index.ts
Fix for https://github.com/mieszko4/react-native-zoom-us/pull/103
> Add webinar_token for android

- index.ts
Closes https://github.com/mieszko4/react-native-zoom-us/issues/117
> Fix providing default language, refactor

- android/src/main/java/ch/milosz/reactnative/RNZoomUsModule.java
> Fixed issue when unmuting video or audio

- android/src/main/java/ch/milosz/reactnative/RNZoomUsModule.java
Fixes https://github.com/mieszko4/react-native-zoom-us/issues/129
> Use webinarToken as join param

- CHANGELOG.md
- README.md
- RNZoomUs.podspec
- android/build.gradle
Closes https://github.com/mieszko4/react-native-zoom-us/issues/138
Closes https://github.com/mieszko4/react-native-zoom-us/issues/132
> Upgrade to the newest ZoomSDK (android and iOS)

- android/src/main/java/ch/milosz/reactnative/RNZoomUsModule.java
* Simplified calls when possible 
* There are still a couple of methods that might need to run from UIThread but still work as is
* Reordered and grouped methods
* Added listener for onMyAudioSourceTypeChanged
> Run api calls from UIThread

- android/src/main/java/ch/milosz/reactnative/RNZoomUsModule.java
- docs/EVENTS.md
- ios/RNZoomUs.h
- ios/RNZoomUs.m
* Get events on iOS to be on par with android
> Get events on iOS and android on par

- android/src/main/java/ch/milosz/reactnative/RNZoomUsModule.java
- docs/EVENTS.md
- ios/RNZoomUs.m
Inspired by https://github.com/react-native-netinfo/react-native-netinfo/pull/487
> Fix warnings for events on rn-0.66

- android/src/main/java/ch/milosz/reactnative/RNZoomUsModule.java
- index.ts
- ios/RNZoomUs.m
> Simplify, remove joinMeetingWithPassword

- README.md
- android/src/main/java/ch/milosz/reactnative/RNZoomUsActivity.java
- docs/CUSTOM-MEETING-ACTIVITY.md
- docs/VIDEO-VIEW.md
Closes https://github.com/mieszko4/react-native-zoom-us/issues/169
> feat: my activity with backward leave

- android/src/main/java/ch/milosz/reactnative/RNZoomUsModule.java
Im not sure this will fix #175 because I cant reproduce, but looking at the error its a very possible fix.
> Possible fix for null userInfo

- android/build.gradle
Closes https://github.com/mieszko4/react-native-zoom-us/issues/190
Thnx @Md-Mudassir47 for debugging this :)
> fix: crash on android

- RNZoomUs.podspec
- android/build.gradle
- android/src/main/java/ch/milosz/reactnative/RNZoomUsModule.java
- ios/RNZoomUs.m
Fixed #196 #180 
This update should very straight forward, just a couple of implementation updates and additions with a ton of bugfixes and finally (partial) android 12 support.
This might also fix issue #194 but cant be sure until I test it more.
[iOS release post](https://8xmdmkir8ctlkfj8dttx.noticeable.news/publications/ios-meeting-sdk-v5-9-6?embed=true)
[Android release post](https://8xmdmkir8ctlkfj8dttx.noticeable.news/publications/android-meeting-sdk-v5-9-6?before=MTY0NjQ0Mjg0OTc2Ng==&embed=true)
> SDK update to 5.9.6

- README.md
Closes https://github.com/mieszko4/react-native-zoom-us/issues/213
> feat(docs): add section about declaring Android permissions

- native.ts
Closes https://github.com/mieszko4/react-native-zoom-us/issues/212
> feat: convert VideoAspectModeEnum to union type

- README.md
- docs/TROUBLESHOOTING.md
Related https://github.com/mieszko4/react-native-zoom-us-test/pull/55
> feat: adjust docs after testing with react-native 0.70

- android/src/main/java/ch/milosz/reactnative/RNZoomUsModule.java
fixes: #237 app not building due to local variable accessed within inner class must be final
> fixes: #237 app not building

- CHANGELOG.md
- README.md
- android/build.gradle
- android/src/main/java/ch/milosz/reactnative/RNZoomUsModule.java
- index.ts
- package-lock.json
- package.json
* https://8xmdmkir8ctlkfj8dttx.noticeable.news/publications/meeting-sdk-android-v5-12-8
* https://8xmdmkir8ctlkfj8dttx.noticeable.news/publications/meeting-sdk-android-v5-13-0
> feat: Upgrade Android to 5.13.1.11014

- CHANGELOG.md
- README.md
- android/build.gradle
- android/src/main/java/ch/milosz/reactnative/RNZoomUsModule.java
- docs/TROUBLESHOOTING.md
- index.ts
- package-lock.json
- package.json
* https://8xmdmkir8ctlkfj8dttx.noticeable.news/publications/meeting-sdk-v5-10-3-patch
* https://8xmdmkir8ctlkfj8dttx.noticeable.news/publications/meeting-sdk-android-v5-10-6
* https://8xmdmkir8ctlkfj8dttx.noticeable.news/publications/meeting-sdk-android-v5-11-0
* https://8xmdmkir8ctlkfj8dttx.noticeable.news/publications/meeting-sdk-v5-11-1-patch
* https://8xmdmkir8ctlkfj8dttx.noticeable.news/publications/meeting-sdk-android-v5-11-3-1
* https://8xmdmkir8ctlkfj8dttx.noticeable.news/publications/meeting-sdk-android-v5-11-10
* https://8xmdmkir8ctlkfj8dttx.noticeable.news/publications/meeting-sdk-android-v5-12-0
* https://8xmdmkir8ctlkfj8dttx.noticeable.news/publications/meeting-sdk-for-android-v5-12-1-hotfix-1
* https://8xmdmkir8ctlkfj8dttx.noticeable.news/publications/meet …
> feat: Upgrade Android to 5.13.1

- android/build.gradle
`lottie` added duplicate - on L40 and L62 (https://github.com/mieszko4/react-native-zoom-us/blob/master/android/build.gradle#L40)
Fix #270
> Remove duplicate lottie implementation

- CHANGELOG.md
- README.md
- docs/TROUBLESHOOTING.md
Related https://github.com/mieszko4/react-native-zoom-us-test/pull/71
> feat: upgrade to react-native 0.72.2

- CHANGELOG.md
- README.md
- android/build.gradle
- android/src/main/java/ch/milosz/reactnative/RNZoomUsModule.java
* https://devsupport.zoom.us/hc/en-us/articles/12499111636621-Zoom-Meeting-SDK-Android-5-13-5
* https://devsupport.zoom.us/hc/en-us/articles/13371333009037-Zoom-Meeting-SDK-Android-5-13-10
Closes https://github.com/mieszko4/react-native-zoom-us/issues/280
> feat: 5.13.10.1257

- README.md
- RNZoomUs.podspec
- docs/IOS-SCREENSHARE.md
- index.ts
- ios/RNZoomUs.m
Closes https://github.com/mieszko4/react-native-zoom-us/issues/290, https://github.com/mieszko4/react-native-zoom-us/issues/326
> Upgrade ios sdk to 5.14.11 and remove clientKey/Secret references

- android/build.gradle
- android/src/main/java/ch/milosz/reactnative/RNZoomUsModule.java
* Change jitpack-zoom-us from from 5.16.2.16555 to 5.17.11.20433
* Bump compileSDK version to 34
* Bumped Android dependencies because we were seeing a blank black screen when accessing the Zoom waiting room
Tested on:
Pixel 4a - Android 13
Pixel 7a - Android 14
Features tested:
- Waiting room
- Reactions
- Chat
- Blurring background
- Video and sound
@cristianblar
@miarevalo10
> Upgrade Android SDK to 5.17.11.20433
